sudo: required

language: node_js

services:
  - docker

node_js:
  - stable

before_install:
  - shopt -s expand_aliases
  - docker pull billryan/gitbook:latest
  - docker pull billryan/gitbook:zh-hans
  - docker pull billryan/gitbook:zh-hant
  - alias gitbook_en='docker run --rm -v "$PWD":/gitbook -p 4000:4000 billryan/gitbook:latest gitbook'
  - alias gitbook_zh_hans='docker run --rm -v "$PWD":/gitbook -p 4000:4000 billryan/gitbook:zh-hans gitbook'
  - alias gitbook_zh_hant='docker run --rm -v "$PWD":/gitbook -p 4000:4000 billryan/gitbook:zh-hant gitbook'

install:
  - gitbook_en install

before_script:
- cp LANGS.md LANGS.md.bak

script:
  - echo "build English ebook"
  - sed '/\(en\/\)/! d' LANGS.md.bak > LANGS.md
  - gitbook_en pdf .
  - gitbook_en epub .
  - gitbook_en mobi .
  - echo "build Simplified Chinese ebook"
  - sed '/\(zh-hans\/\)/! d' LANGS.md.bak > LANGS.md
  - gitbook_zh_hans pdf .
  - gitbook_zh_hans epub .
  - gitbook_zh_hans mobi .
  - echo "build Traditional Chinese ebook"
  - sed '/\(zh-tw\/\)/! d' LANGS.md.bak > LANGS.md
  - gitbook_zh_hant pdf .
  - gitbook_zh_hant epub .
  - gitbook_zh_hant mobi .
  - echo "build HTML pages"
  - cp LANGS.md.bak LANGS.md
  - gitbook_en build .
  - ls -alh

before_deploy:
  - tar czvf book_html.tar.gz _book/

deploy:
  - provider: pages
    skip-cleanup: true
    github-token:
      secure: B/dqY0sC9I0Uu5o3HVHouX/mfLTUH/dt16IsBdm+sZQW+/YeTUTGwpx+Vl5lXpMhUoxrh60Qxt0KbnqvPqAxsPXGMH2Mhl1E5lgvMYViOGQyx9JJuuba+GWOzD+r2+XOUsqBzOCUhvC7iZbuGiWYvV2+4noAmAoKa1pO1j2yxiI=
    keep-history: false
    local-dir: _book
    on:
      branch: master
    target-branch: gh-pages
  - provider: releases
    api_key:
      secure: B/dqY0sC9I0Uu5o3HVHouX/mfLTUH/dt16IsBdm+sZQW+/YeTUTGwpx+Vl5lXpMhUoxrh60Qxt0KbnqvPqAxsPXGMH2Mhl1E5lgvMYViOGQyx9JJuuba+GWOzD+r2+XOUsqBzOCUhvC7iZbuGiWYvV2+4noAmAoKa1pO1j2yxiI=
    file:
      - book_html.tar.gz
      - book_en.epub
      - book_en.mobi
      - book_en.pdf
      - book_zh-hans.epub
      - book_zh-hans.mobi
      - book_zh-hans.pdf
      - book_zh-tw.epub
      - book_zh-tw.mobi
      - book_zh-tw.pdf
    skip_cleanup: true
    on:
      repo: billryan/algorithm-exercise

after_success:
  - ls -lh

branches:
  only:
  - master
